### ISSUE TITLE
Improve replacment of running trains

### ISSUE THREAD

**Issue by 0ptera** [robot256/MultipleUnitTrainControl#3]
Replacing driving trains can lead to massive crashes and can also fail to reconnect replaced locomotives.
![2019-04-08-10-53-05-5728247](https://user-images.githubusercontent.com/8436934/55711263-a82a2900-59ec-11e9-933f-fabfa715233b.png)

This can be prevented by only replacing trains at safe times:
1. Enabling the mod should replace trains during on_configuration_changed.
  The game in this state is not running and all trains are perfectly stationary. However reconnecting rolling stock on curves and switches could still be an issue.
2. Enabling mid game should queue the train and only replace when it's save to do so.
  Wait for on_train_changed_state. Safe states are when the train is stopped:
    - defines.train_state.wait_station -- the safest state possible, it's least likely that trains are on a junction and fail to reconnect.
    - defines.train_state.wait_signal
    - defines.train_state.no_path
    - defines.train_state.no_schedule
    - defines.train_state.manual_control

0.1.12 also has some errors:
1. using tech unlock does not replace locomotives to MU
2. replaced trains don't toggle automatic mode back on
  The reason trains are coasting to a stop ignoring red signals and crash into another is due to this.
  You have to store LuaTrain.manual_mode and restore it after you replaced locomotives.

**Comment by robot256** [comment]
I have been thinking about only replacing trains when they are stopped.  Using the train state is a great idea to do this.  I think on_configuration_change should also wait for a good train state, since even though the game is stopped, the locomotive might be on an intersection and have incorrect replacement.  I'm also guessing that I should take out some of my tick-spreading logic, so it can replace an entire train in one tick.  The important part is to queue on_train_created events, because otherwise they will interrupt ongoing replacements.

The tech-unlock not working was intended to prevent replacements while moving, and automatic mode not restoring was intended to make crashes less likely with moving replacements.  Making all replacements happen when stopped/safe will make these safe to turn back on.

**Comment by 0ptera** [comment]
Well the way I had to convert 200 LTN trains with tech unlock was far from comfortable.
Disable one depot a time, wait for all trains to come back, hop into each train, disconnect the frontmost or backmost locomotive, reconnect to force your mot to convert to MU, set the train back to auto mode and proceed with the next train.
Practically it's just rapidly pressing enter-v-g-j-enter and the direction keys, but it should be automated.

**Comment by robot256** [comment]
In that situation, you could set mod to disabled, then back to tech-unlock after you turned off all the depots.  Any mode change will force all trains on the map to be reprocessed.  But now that I know the rest of it basically works and people like it, I will work on making it more transparent and reliable.

**Comment by robot256** [comment]
Would you like to send me that map with 200 trains?  It would make it very easy to spot problems when I am testing.

**Comment by 0ptera** [comment]
That save is quite large and requires some customized mods.
save: https://drive.google.com/open?id=17bU3eJGqcvGlNOFwKEB4wMJ-MttCpIaT
mods: https://drive.google.com/open?id=1A1vlRtpbPQlWDjRnuG2qkN3n_TXQI3kb

PS: Please let me know how many ups you get with this, especially how much update time Inv Sensor and LTN use for you.

**Comment by robot256** [comment]
That is a very impressive map!  With my release 0.1.13, I believe I have implemented the changes you suggested.  I loaded your map, downloaded the mod (and FARL 3.1.5, because the version in the pack you sent me crashed on 0.17.26), and after about five minutes, all the trains on the map had been replaced.  Couldn't find any derailments or explosions or stopped trains.  LTN seemed to recover just fine, though it gave a "delivery cancelled (train invalid)" message for most of the trains when they were replaced.  Let me know if you find any more issues!
